FROM bde2020/hive:2.3.2-postgresql-metastore
COPY ./jars/aws-java-sdk-bundle-1.11.1026.jar /opt/hadoop-2.7.4/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.1026.jar
COPY ./jars/hadoop-aws-3.3.3.jar /opt/hadoop-2.7.4/share/hadoop/tools/lib/hadoop-aws-3.3.3.jar
COPY ./jars/hadoop-common-3.3.3.jar /opt/hadoop-2.7.4/share/hadoop/tools/lib/hadoop-common-3.3.3.jar